/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import infraestructura.controllers.Controller;

import javax.swing.*;

public class App {


    public static void main(String[] args) {


        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        Controller control = new Controller();



    }
}
